[project]
name = "dani-api"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Daniela Algerydh", email = "danielaalgerydh@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "fastapi>=0.140.0",
    "openai>=2.48.0",
    "pydantic-settings>=2.14.2",
    "qdrant-client>=1.18.0",
    "uvicorn[standard]>=0.51.0",
]

[project.scripts]
dani-api = "dani_api:main"

[build-system]
requires = ["uv_build>=0.9.17,<0.10.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "ruff>=0.16.0",
]
